### ISSUE TITLE
Add a support of named parameters

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando/lizzy-client#18]
Senza supports named parameters, so in YAML file I can define something like

```
SenzaInfo:
  StackName: my-stack-name
  Parameters:
    - ImageVersion:
        Description: "Docker image version of seo-descriptions-api-staging."
    - ScalyrAccountKey:
        Description: "Scalyr (logs aggregator) account key."
```

and then use parameters in the YAML definition:

```
      TaupageConfig:
        application_version: "{{Arguments.ImageVersion}}"
        source: "myserver/teamid/app:{{Arguments.ImageVersion}}"
        scalyr_account_key: {{Arguments.ScalyrAccountKey}}
```

Seems that currently `lizzy create` doesn't have a support of named parameters. Would be nice to have it because otherwise we need to hardcode all template parameters into the YAML file (including sensitive data like keys and accounts)
